### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by zhangchanglong** [linyimin0812/spring-startup-analyzer#12]
Error opening zip file or JAR manifest missing : root/spring-startup-analyzer/lib/spring-profiler-agent.jar
Error occurred during initialization of VM
agent library failed to init: instrument

linux环境，java8, jar是有的，权限也没什么问题

**Comment by linyimin0812** [comment]
这个`root/`是`home`目录吗？看起来像是找不到相关文件，需要讲`spring-startup-analyzer`放到`home`目录下

**Comment by zhangchanglong** [comment]
改成/home了， 启动不报错了，但是  没生成log文件， 也没打印 那个日志

启动命令这么写的：
java  -Xms500m -Xmx500m -Xmn250m -Xss256k -jar -Dserver.port=9098  -Dfile.encoding=utf-8 -Dspring-startup-analyzer.app.health.check.timeout=30 -javaagent:/home/spring-startup-analyzer/lib/spring-profi
ler-agent.jar -jar /dzzb/usr/local/jar-dir/interface.jar

**Comment by linyimin0812** [comment]
在终端执行一下命令`echo $HOME`，看一下home目录的路径，然后把`spring-startup-analyzer`放到此目录下

**Comment by zhangchanglong** [comment]
开始报 /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found 
 
 
 后来我找了一个稍高版本的 so 又报 /lib64/libc.so.6: version `GLIBC_2.18'
 
 能否把您的so直接给我发下

**Comment by zhangchanglong** [comment]
开始报 /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found 
 
 
 后来我找了一个稍高版本的 so 又报 /lib64/libc.so.6: version `GLIBC_2.18'
 
 能否把您的so直接给我发下

**Comment by zhangchanglong** [comment]
刚刚在服务器上 把软连接 搞坏了， 不敢试了。 项目 是 挺好的，加油

**Comment by qq3961792** [comment]
Error occurred during initialization of VM
agent library failed to init: instrument

请问这个报错咋解决的，我也遇到同样的问题了
