### ISSUE TITLE
Mac 怎么启动呢

### ISSUE THREAD

**Issue by longbiaob** [linyimin0812/spring-startup-analyzer#13]

**Comment by linyimin0812** [comment]
先将安装包解压到$HOME目录

在Idea中启动的话，在VM Options中指定一下agent的路径`-javaagent:$HOME/spring-startup-analyzer/lib/spring-profiler-agent.jar`
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/17776713/cb63c31e-b79f-444c-a614-68f9c23e6059)

命令行启动的话加一下参数：`-javaagent:$HOME/spring-startup-analyzer/lib/spring-profiler-agent.jar`

$HOME换成自己的`home`目录
