### ISSUE TITLE
please support offline env

### ISSUE THREAD

**Issue by usc** [linyimin0812/spring-startup-analyzer#35]
startup-analysis.html link https://cdn.tailwindcss.com and https://cdn.skypack.dev/hyperapp web resources.

please support offline env, thanks.

**Comment by linyimin0812** [comment]
> startup-analysis.html link https://cdn.tailwindcss.com and https://cdn.skypack.dev/hyperapp web resources.
> 
> please support offline env, thanks.

version v2.0.7 has supported offline mode
