### ISSUE TITLE
is it support win10？

### ISSUE THREAD

**Issue by PretendMask** [linyimin0812/spring-startup-analyzer#42]
good afternoon sir.
【my configuration as below】：
computer operation syste：win10
spring-startup-analyzer：v2.0.6
jdk-version：open-jdk17
springbootversion：3.1.1

【question desc】：
i am create a new springboot project，it not contains anyone other maven pom，at my install jar after，i try start it，cmd line as below：
java -jar demo-0.0.1-SNAPSHOT.jar -javaagent:C:/xxx/Downloads/Analyzer/lib/spring-profiler-agent.jar

i am ensure my spring-profiler-agent.jar path no mistake，but，why start springboot application at after, i don't see "======= spring-startup-analyzer finished, click http://localhost:8065 to visit details. ======
" infomation，aslo not any other err infomation，just like a normal springboot start the same，why？extra i don't see the type of support  of  Analyzer project

**Comment by linyimin0812** [comment]
Have you configured the `spring-startup-analyzer.app.health.check.endpoints` option?

**Comment by linyimin0812** [comment]
You need to implement a health check interface and then configure the `spring-startup-analyzer.app.health.check.endpoints` option.

For example, the health check interface as follow:

```java
@RestController
public class Home {
        @RequestMapping({"/health"})
    public String index(Model model) {
        return "index";
    }
}
```

and then you need to set `-Dspring-startup-analyzer.app.health.check.endpoints=http://localhost:7002/health`

**Comment by PretendMask** [comment]
> You need to implement a health check interface and then configure the `spring-startup-analyzer.app.health.check.endpoints` option.
> 
> For example, the health check interface as follow:
> 
> ```java
> @RestController
> public class Home {
>         @RequestMapping({"/health"})
>     public String index(Model model) {
>         return "index";
>     }
> }
> ```
> 
> and then you need to set `-Dspring-startup-analyzer.app.health.check.endpoints=http://localhost:7002/health`

i have add this start command param now：“-Dspring-startup-analyzer.app.health.check.endpoints=http://localhost:7002/health”，now my springboot demo project start console appearing  "Server listening on port 8065"，and appearing log/startup.log file at my Analyzer directory，but, I still cannot access local port 8065 to view my bean analysis logs，the status of this webpage is ERR_ EMPTY_ RESPONSE，then, i am findout my spriingboot-Analyzer startup.log，everything is normal log information，

just have two warn logs is ：“Current OS do not support AsyncProfiler, Only support Linux/Mac.” with “AsyncProfiler instance is null, can't execute start command.”

my goal is when the application starts in Java Agent mode, it is dynamically loaded into the jvm and runs together with the application. then, I view my bean analysis log on a page


what mistakes may I have made,please point out that ,I will try and findout. thank you for taking the valuable time to answer

**Comment by linyimin0812** [comment]
You can check if output/*-analyzer.html exists and the html relies on online resources: https://cdn.tailwindcss.com and https://cdn.skypack.dev/hyperapp ,ensure your environment can access these online resources.

**Comment by linyimin0812** [comment]
> > You need to implement a health check interface and then configure the `spring-startup-analyzer.app.health.check.endpoints` option.
> > For example, the health check interface as follow:
> > ```java
> > @RestController
> > public class Home {
> >         @RequestMapping({"/health"})
> >     public String index(Model model) {
> >         return "index";
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then you need to set `-Dspring-startup-analyzer.app.health.check.endpoints=http://localhost:7002/health`
> 
> i have add this start command param now：“-Dspring-startup-analyzer.app.health.check.endpoints=[http://localhost:7002/health”，now](http://localhost:7002/health%E2%80%9D%EF%BC%8Cnow) my springboot demo project start console appearing "Server listening on port 8065"，and appearing log/startup.log file at my Analyzer directory，but, I still cannot access local port 8065 to view my bean analysis logs，the status of this webpage is ERR_ EMPTY_ RESPONSE，then, i am findout my spriingboot-Analyzer startup.log，everything is normal log information，
> 
> just have two warn logs is ：“Current OS do not support AsyncProfiler, Only support Linux/Mac.” with “AsyncProfiler instance is null, can't execute start command.”
> 
> my goal is when the application starts in Java Agent mode, it is dynamically loaded into the jvm and runs together with the application. then, I view my bean analysis log on a page
> 
> what mistakes may I have made,please point out that ,I will try and findout. thank you for taking the valuable time to answer

The new version v2.0.7 has implemented CDN resource localization, you have a try again.
