### ISSUE TITLE
No Thread Wall Clock Profile generated ?

### ISSUE THREAD

**Issue by MingningShao** [linyimin0812/spring-startup-analyzer#46]
![Thread Wall Clock Profile Missing](https://github.com/linyimin0812/spring-startup-analyzer/assets/13358443/9f7aa4ac-24e1-4bc8-b9fe-203c20a6270d)

Windows 10

It seems that the current release don't support Windows ?

Following the usage and profiled generated, but no Thread Wall Clock Profile ?

**Comment by linyimin0812** [comment]
> ![Thread Wall Clock Profile Missing](https://user-images.githubusercontent.com/13358443/257519091-9f7aa4ac-24e1-4bc8-b9fe-203c20a6270d.jpg)
> 
> Windows 10
> 
> It seems that the current release don't support Windows ?
> 
> Following the usage and profiled generated, but no Thread Wall Clock Profile ?

版本v2.0.9已支持在windows下产生火焰图，如果还需要的话，可以更新一下版本再试一下
