### ISSUE TITLE
分析文件为空

### ISSUE THREAD

**Issue by BYNepenthe** [linyimin0812/spring-startup-analyzer#49]
1.正常启动 spring-startup-analyzer；
2.正常启动要分析的项目；
3.打开http://localhost:8065 地址，页面内容为空；
4.日志文件中未看到 报错信息；
6.spring-startup-analyzer 文件夹确认放在了 HOME 目录；

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/7778022/a9c7ab4d-6ee3-4c99-aa96-50f8dc5fb085)

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/7778022/a8619a1d-83c1-4cd5-932d-7bf7c0de8542)

**Comment by linyimin0812** [comment]
可以按照下面的思路排查一下:
1. 看一下$HOME/spring-startup-analyzer/output文件夹下有没有生成html文件，没有的话说明启动过程存在问题，看一下logs/startup.log日志有没有报错
2. 如果有html文件的话，在chrome里F12打开console 看一下是否有报错

**Comment by BYNepenthe** [comment]
生成的 html 文件报这个错误

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/7778022/25a25150-0e12-4573-9ea6-4fbada7e2009)

**Comment by linyimin0812** [comment]
是什么系统呀？而且日志文件里有报什么错嘛？看起来采集的数据都为空
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/17776713/c1133146-f446-4122-a748-30d34967cdef)

**Comment by linyimin0812** [comment]
如果方便的话，也提供一下spring的版本吧，我看一下是不是不支持该版本，所以采集不到数据

**Comment by BYNepenthe** [comment]
springboot 项目
springboot 版本：2.6.6

idea 中运行的这个项目

spring-startup-analyzer，配置文件中配置的监控地址如下：
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/7778022/78cfb92b-bebf-454b-9a25-2e281b3fb3fe)

命令行中运行的 spring-startup-analyzer，执行命令如下：
java -jar -javaagent:${HOME}/spring-startup-analyzer/lib/spring-profiler-agent.jar

**Comment by linyimin0812** [comment]
是windows嘛？

**Comment by linyimin0812** [comment]
> springboot 项目 springboot 版本：2.6.6
> 
> idea 中运行的这个项目
> 
> spring-startup-analyzer，配置文件中配置的监控地址如下： ![image](https://user-images.githubusercontent.com/7778022/257711316-78cfb92b-bebf-454b-9a25-2e281b3fb3fe.png)
> 
> 命令行中运行的 spring-startup-analyzer，执行命令如下： java -jar -javaagent:${HOME}/spring-startup-analyzer/lib/spring-profiler-agent.jar

如果是在IDEA中启动的话，需要在VM options中指定agent，直接用命令行启动会采集不到数据

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/17776713/b0a4f254-7e2c-48ea-8252-af23bdd26001)

**Comment by BYNepenthe** [comment]
可以了，多谢，没理解好文档中的 “在IDEA中启动的话，需要在VM options中指定agent”，以为是 IDEA 中启动 spring-startup-analyzer 这个项目呢

**Comment by MeetinaXD** [comment]
尝试了 `openjdk 21 (arm)` 能够正常生成文件，可能是版本兼容性问题
