### ISSUE TITLE
window idea 无法读取vm参数

### ISSUE THREAD

**Issue by sicychds** [linyimin0812/spring-startup-analyzer#5]
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/133948495/729b85ab-51c6-4aac-878e-33715960661b)
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/133948495/3fcd615c-8ed1-45d0-b11f-a0834a33eb6f)
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/133948495/209d30d4-4c76-49d1-bf09-78bb879637d5)

**Comment by linyimin0812** [comment]
可以直接修改配置文件$HOME/spring-startup-analyzer/config/spring-startup-analyzer.properties，后续我看一下为什么无法读取vm参数

**Comment by linyimin0812** [comment]
> ![image](https://user-images.githubusercontent.com/133948495/255454805-729b85ab-51c6-4aac-878e-33715960661b.png) ![image](https://user-images.githubusercontent.com/133948495/255454858-3fcd615c-8ed1-45d0-b11f-a0834a33eb6f.png) ![image](https://user-images.githubusercontent.com/133948495/255454905-209d30d4-4c76-49d1-bf09-78bb879637d5.png)

版本v2.0.4已修复
