### ISSUE TITLE
请问为什么看不到火焰图?我是Windows,v2.0.7

### ISSUE THREAD

**Issue by sabersword** [linyimin0812/spring-startup-analyzer#54]
请问为什么看不到火焰图?我是Windows,v2.0.7
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/32424539/bff2f2b5-7a9f-40d9-a467-71c47797da9b)

**Comment by linyimin0812** [comment]
火焰图是基于[async-profiler](https://github.com/async-profiler/async-profiler)，只支持linux和mac，所以Windows下没有火焰图

**Comment by linyimin0812** [comment]
> 请问为什么看不到火焰图?我是Windows,v2.0.7 ![image](https://user-images.githubusercontent.com/32424539/257851020-bff2f2b5-7a9f-40d9-a467-71c47797da9b.png)

版本v2.0.9已支持windows下火焰图，如果还需要的话，可以更新一下版本

**Comment by yichengxian** [comment]
> 火焰图是基于[async-profiler](https://github.com/async-profiler/async-profiler)，只支持linux和mac，所以Windows下没有火焰图

我想问一下，是不是必须等20分钟才能有结果，我没看到说明文档相关描述

**Comment by linyimin0812** [comment]
> > 火焰图是基于[async-profiler](https://github.com/async-profiler/async-profiler)，只支持linux和mac，所以Windows下没有火焰图
> 
> 我想问一下，是不是必须等20分钟才能有结果，我没看到说明文档相关描述

「配置项」那块有相关的描述

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/17776713/9e026a0f-5e3b-432f-8e52-57be37dd4835)

**Comment by sabersword** [comment]
感谢支持Windows的火焰图

**Comment by sabersword** [comment]
> > 请问为什么看不到火焰图?我是Windows,v2.0.7 ![image](https://user-images.githubusercontent.com/32424539/257851020-bff2f2b5-7a9f-40d9-a467-71c47797da9b.png)
> 
> 版本v2.0.9已支持windows下火焰图，如果还需要的话，可以更新一下版本

感谢支持Windows的火焰图
