### ISSUE TITLE
windows idea 无法输出 ======= spring-startup-analyzer finished, click http://localhost:xxxx to visit details. ======

### ISSUE THREAD

**Issue by 2259289435** [linyimin0812/spring-startup-analyzer#6]
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/23507198/3f6cb26f-f213-461d-9b22-4b7f778c335c)
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/23507198/9972a04b-607e-4169-bb40-c77debcbcbee)
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/23507198/543001cb-ddf4-4a79-920c-3a157f93ac26)

请问还可以提供什么？

**Comment by 2259289435** [comment]
http://localhost:8065也访问不了

**Comment by 2259289435** [comment]
把agent整个包放到家目录而不是家目录下的Downloads下面，不报文件找不到了。但还是访问不了8065
![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/23507198/ec88567e-e80b-4165-b88c-0630610bf792)

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/23507198/4e964be3-a378-41d1-b324-b551c70ecacb)

**Comment by jmychou** [comment]
> 把agent整个包放到家目录而不是家目录下的Downloads下面，不报文件找不到了。但还是访问不了8065 ![image](https://user-images.githubusercontent.com/23507198/255459625-ec88567e-e80b-4165-b88c-0630610bf792.png)
> 
> ![image](https://user-images.githubusercontent.com/23507198/255459539-4e964be3-a378-41d1-b324-b551c70ecacb.png)

@2259289435 @linyimin0812  这个页面貌似要访问外网CDN资源，局域网是不是不支持查看？😂

**Comment by 2259289435** [comment]
找到原因了，是配置的vm参数读不到，还是按20分钟那个，然后默认的健康检查那个去，要改配置文件

**Comment by linyimin0812** [comment]
> > 把agent整个包放到家目录而不是家目录下的Downloads下面，不报文件找不到了。但还是访问不了8065 ![image](https://user-images.githubusercontent.com/23507198/255459625-ec88567e-e80b-4165-b88c-0630610bf792.png)
> > ![image](https://user-images.githubusercontent.com/23507198/255459539-4e964be3-a378-41d1-b324-b551c70ecacb.png)
> 
> @2259289435 @linyimin0812 这个页面貌似要访问外网CDN资源，局域网是不是不支持查看？😂

这个确实依赖了线上的CDN资源，得看看怎么把这些资源放在本地

**Comment by linyimin0812** [comment]
> 找到原因了，是配置的vm参数读不到，还是按20分钟那个，然后默认的健康检查那个去，要改配置文件

vm参数读不到在v2.0.4版本中修复了

**Comment by linyimin0812** [comment]
> > 把agent整个包放到家目录而不是家目录下的Downloads下面，不报文件找不到了。但还是访问不了8065 ![image](https://user-images.githubusercontent.com/23507198/255459625-ec88567e-e80b-4165-b88c-0630610bf792.png)
> > ![image](https://user-images.githubusercontent.com/23507198/255459539-4e964be3-a378-41d1-b324-b551c70ecacb.png)
> 
> @2259289435 @linyimin0812 这个页面貌似要访问外网CDN资源，局域网是不是不支持查看？😂

有兴趣搞一下不？😂将cdn资源放到本地
