### ISSUE TITLE
日志框架兼容问题

### ISSUE THREAD

**Issue by zhaoxiaojie0415** [linyimin0812/spring-startup-analyzer#73]
AsyncProxyBeanPostProcessor 异步bean用的logger是logback框架的（scope为provided），如果本身java服务是使用log4j2框架，则主动引入logback会有兼容问题，如果不引入在异步bean加载的时候则会有NoClassFound错误。

这里有什么好的解决方法吗
比如异步加载的日志跟随业务的日志输出呢，不再单独打到startup日志里，打印日志采用sl4fj
或者增加一个log4j版本的实现，运行时根据配置使用哪一种logger实现

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/13363629/0238e080-3d81-4b80-aa26-bee087a1857b)

**Comment by hokage-dev** [comment]
可以使用最新版v2.0.10，这个版本移除了logback框架

**Comment by zhaoxiaojie0415** [comment]
> 可以使用最新版v2.0.10，这个版本移除了logback框架

好的，多谢啦
