### ISSUE TITLE
代码疑惑

### ISSUE THREAD

**Issue by lnsane** [linyimin0812/spring-startup-analyzer#77]
https://github.com/linyimin0812/spring-startup-analyzer/blob/75596ce9d4de08e39c628d574d00e41f7c49a05a/spring-profiler-core/src/main/java/io/github/linyimin0812/profiler/core/enhance/ProfilerClassFileTransformer.java#L50

这个类增强后，下面会执行什么逻辑，有点懵？

**Comment by yichengxian** [comment]
你现在不看了？
