### ISSUE TITLE
异步执行初始化方法并发情况下可能造成的启动错误

### ISSUE THREAD

**Issue by wenpanwenpan** [linyimin0812/spring-startup-analyzer#80]
<img width="1367" alt="image" src="https://github.com/linyimin0812/spring-startup-analyzer/assets/39766740/f9fc7752-4e0f-42fc-8374-bbc4b9aab48a">
上图中线程池异步执行XXXBean的初始化方法（比如：加载一些配置），如果此时主线程在启动过程中需要依赖异步初始化方法加载的配置做判断，此时是否会有并发问题。在异步方法执行过程中如果有其他线程调用XXXBean的方法，此时是否应该阻塞等待异步线程执行完毕，以保证线程安全？

**Comment by linyimin0812** [comment]
是的，可能会存在这个问题，最好是对不被依赖的Bean进行异步化，如果对被依赖的Bean进行异步化，需要做好测试

**Comment by wenpanwenpan** [comment]
如果有依赖，是否可以考虑让依赖的线程同步等待，直到依赖的初始化方法执行完成，然后再继续执行

**Comment by linyimin0812** [comment]
> 如果有依赖，是否可以考虑让依赖的线程同步等待，直到依赖的初始化方法执行完成，然后再继续执行

这种方式感觉有点困难，目前根据分析报告是可以知道根Bean（不被依赖的Bean），每个根Bean用一个线程进行异步初始化，这样就不会存在依赖的问题

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/17776713/83aacc43-7e8e-4055-b74f-7385b356f46d)
